-- Phase 1bis — INSERT 39 new MD form definitions into app_form
-- Idempotent via ON CONFLICT.

BEGIN;

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md52programStatus', 'MD.52 - Program Status', 'md52programStatus',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md52programStatus", "name": "MD.52 - Program Status", "tableName": "md52programStatus", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md53priority', 'MD.53 - Priority', 'md53priority',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md53priority", "name": "MD.53 - Priority", "tableName": "md53priority", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md54reportingFreq', 'MD.54 - Reporting Frequency', 'md54reportingFreq',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md54reportingFreq", "name": "MD.54 - Reporting Frequency", "tableName": "md54reportingFreq", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md55geographicScope', 'MD.55 - Geographic Scope', 'md55geographicScope',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md55geographicScope", "name": "MD.55 - Geographic Scope", "tableName": "md55geographicScope", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md56targetingStrat', 'MD.56 - Targeting Strategy', 'md56targetingStrat',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md56targetingStrat", "name": "MD.56 - Targeting Strategy", "tableName": "md56targetingStrat", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md57priorityModel', 'MD.57 - Priority Model', 'md57priorityModel',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md57priorityModel", "name": "MD.57 - Priority Model", "tableName": "md57priorityModel", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md58benefitItemType', 'MD.58 - Benefit Item Type', 'md58benefitItemType',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md58benefitItemType", "name": "MD.58 - Benefit Item Type", "tableName": "md58benefitItemType", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md59ruleType', 'MD.59 - Rule Type', 'md59ruleType',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md59ruleType", "name": "MD.59 - Rule Type", "tableName": "md59ruleType", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md60evalStrategy', 'MD.60 - Evaluation Strategy', 'md60evalStrategy',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md60evalStrategy", "name": "MD.60 - Evaluation Strategy", "tableName": "md60evalStrategy", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md61approvalFlow', 'MD.61 - Approval Workflow', 'md61approvalFlow',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md61approvalFlow", "name": "MD.61 - Approval Workflow", "tableName": "md61approvalFlow", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md62monitoringApp', 'MD.62 - Monitoring Approach', 'md62monitoringApp',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md62monitoringApp", "name": "MD.62 - Monitoring Approach", "tableName": "md62monitoringApp", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md63dataCollMethod', 'MD.63 - Data Collection Method', 'md63dataCollMethod',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md63dataCollMethod", "name": "MD.63 - Data Collection Method", "tableName": "md63dataCollMethod", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md64documentStatus', 'MD.64 - Document Status', 'md64documentStatus',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md64documentStatus", "name": "MD.64 - Document Status", "tableName": "md64documentStatus", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md65docRejReason', 'MD.65 - Document Rejection Reason', 'md65docRejReason',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md65docRejReason", "name": "MD.65 - Document Rejection Reason", "tableName": "md65docRejReason", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md66eligibStatus', 'MD.66 - Preliminary Eligibility Status', 'md66eligibStatus',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md66eligibStatus", "name": "MD.66 - Preliminary Eligibility Status", "tableName": "md66eligibStatus", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md67mobileMoneyProv', 'MD.67 - Mobile Money Provider', 'md67mobileMoneyProv',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md67mobileMoneyProv", "name": "MD.67 - Mobile Money Provider", "tableName": "md67mobileMoneyProv", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md68appealType', 'MD.68 - Appeal Type', 'md68appealType',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md68appealType", "name": "MD.68 - Appeal Type", "tableName": "md68appealType", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md69entityType', 'MD.69 - Related Entity Type', 'md69entityType',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md69entityType", "name": "MD.69 - Related Entity Type", "tableName": "md69entityType", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md70originalDecision', 'MD.70 - Original Decision', 'md70originalDecision',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md70originalDecision", "name": "MD.70 - Original Decision", "tableName": "md70originalDecision", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md71appealGrounds', 'MD.71 - Appeal Grounds', 'md71appealGrounds',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md71appealGrounds", "name": "MD.71 - Appeal Grounds", "tableName": "md71appealGrounds", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md72appealStatus', 'MD.72 - Appeal Status', 'md72appealStatus',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md72appealStatus", "name": "MD.72 - Appeal Status", "tableName": "md72appealStatus", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md73resolutionDec', 'MD.73 - Resolution Decision', 'md73resolutionDec',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md73resolutionDec", "name": "MD.73 - Resolution Decision", "tableName": "md73resolutionDec", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md74escalationLevel', 'MD.74 - Escalation Level', 'md74escalationLevel',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md74escalationLevel", "name": "MD.74 - Escalation Level", "tableName": "md74escalationLevel", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md75particStatus', 'MD.75 - Participation Status', 'md75particStatus',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md75particStatus", "name": "MD.75 - Participation Status", "tableName": "md75particStatus", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md76exitReason', 'MD.76 - Exit Reason', 'md76exitReason',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md76exitReason", "name": "MD.76 - Exit Reason", "tableName": "md76exitReason", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md77satisfactionRtg', 'MD.77 - Satisfaction Rating', 'md77satisfactionRtg',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md77satisfactionRtg", "name": "MD.77 - Satisfaction Rating", "tableName": "md77satisfactionRtg", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md78notifChannel', 'MD.78 - Notification Channel', 'md78notifChannel',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md78notifChannel", "name": "MD.78 - Notification Channel", "tableName": "md78notifChannel", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md79notifStatus', 'MD.79 - Notification Status', 'md79notifStatus',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md79notifStatus", "name": "MD.79 - Notification Status", "tableName": "md79notifStatus", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md80notifCategory', 'MD.80 - Notification Category', 'md80notifCategory',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md80notifCategory", "name": "MD.80 - Notification Category", "tableName": "md80notifCategory", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md81sendTiming', 'MD.81 - Send Timing', 'md81sendTiming',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md81sendTiming", "name": "MD.81 - Send Timing", "tableName": "md81sendTiming", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md82yieldSource', 'MD.82 - Yield Source', 'md82yieldSource',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md82yieldSource", "name": "MD.82 - Yield Source", "tableName": "md82yieldSource", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md83yieldStatus', 'MD.83 - Yield/Production Status', 'md83yieldStatus',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md83yieldStatus", "name": "MD.83 - Yield/Production Status", "tableName": "md83yieldStatus", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md84seedType', 'MD.84 - Seed Type', 'md84seedType',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md84seedType", "name": "MD.84 - Seed Type", "tableName": "md84seedType", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md85seedSource', 'MD.85 - Seed/Input Source', 'md85seedSource',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md85seedSource", "name": "MD.85 - Seed/Input Source", "tableName": "md85seedSource", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md86fertilizerType', 'MD.86 - Fertilizer Type', 'md86fertilizerType',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md86fertilizerType", "name": "MD.86 - Fertilizer Type", "tableName": "md86fertilizerType", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md87irrigationType', 'MD.87 - Irrigation Type', 'md87irrigationType',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md87irrigationType", "name": "MD.87 - Irrigation Type", "tableName": "md87irrigationType", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md88harvestDispos', 'MD.88 - Harvest Disposition', 'md88harvestDispos',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md88harvestDispos", "name": "MD.88 - Harvest Disposition", "tableName": "md88harvestDispos", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md89shockImpactLvl', 'MD.89 - Shock Impact Level', 'md89shockImpactLvl',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md89shockImpactLvl", "name": "MD.89 - Shock Impact Level", "tableName": "md89shockImpactLvl", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

INSERT INTO app_form (appid, appversion, formid, name, tablename, json, datecreated, datemodified)
VALUES ('farmersPortal', 1, 'md90harvestStatus', 'MD.90 - Harvest Record Status', 'md90harvestStatus',
        $${"elements": [{"elements": [{"elements": [{"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "code", "label": "Code", "maxlength": "50", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "name", "label": "Name", "maxlength": "200", "required": "True", "validator": {"className": "org.joget.apps.form.lib.DefaultValidator", "properties": {"mandatory": "true"}}}}, {"className": "org.joget.apps.form.lib.TextArea", "properties": {"id": "description", "label": "Description", "rows": "3"}}, {"className": "org.joget.apps.form.lib.TextField", "properties": {"id": "displayOrder", "label": "Display Order", "size": "5", "storeNumeric": "true"}}, {"className": "org.joget.apps.form.lib.Radio", "properties": {"id": "isActive", "label": "Active", "options": [{"value": "Y", "label": "Yes"}, {"value": "N", "label": "No"}], "value": "Y"}}], "className": "org.joget.apps.form.model.Column", "properties": {"width": "100%"}}], "className": "org.joget.apps.form.model.Section", "properties": {"id": "section1", "label": "Lookup Entry"}}], "className": "org.joget.apps.form.model.Form", "properties": {"id": "md90harvestStatus", "name": "MD.90 - Harvest Record Status", "tableName": "md90harvestStatus", "loadBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}, "storeBinder": {"className": "org.joget.apps.form.lib.WorkflowFormBinder", "properties": {}}}}$$, NOW(), NOW())
ON CONFLICT (appid, appversion, formid) DO UPDATE
  SET name=EXCLUDED.name, tablename=EXCLUDED.tablename, json=EXCLUDED.json, datemodified=NOW();

COMMIT;
