#!/usr/bin/env bash
# Sync deployed Joget app state back to the repo, commit, optionally push.
#
# The "operator-friendly ritual" wrapper around tooling/sync_pull.py.
# Per ADR-033 (bidirectional app-state sync).
#
# Usage:
#   tooling/sync.sh              pull + commit (no push)
#   tooling/sync.sh --push       pull + commit + push to origin/main
#   tooling/sync.sh --dry-run    pull only, show diff, no commit
#   tooling/sync.sh --no-commit  pull only, leave changes staged for manual commit
#
# Credentials:
#   Reads PGPASSWORD from environment if set, otherwise from
#   ~/IdeaProjects/rsr/secrets/lst-credentials.txt by grep'ing the
#   "Password: " line. If neither works, the script aborts with a
#   clear error.

set -euo pipefail

# ─── Locate repo root ────────────────────────────────────────────────────
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
cd "$REPO_ROOT"

# ─── Resolve PGPASSWORD ──────────────────────────────────────────────────
if [[ -z "${PGPASSWORD:-}" ]]; then
    CRED_FILE="${HOME}/IdeaProjects/rsr/secrets/lst-credentials.txt"
    if [[ ! -f "$CRED_FILE" ]]; then
        # Fall back to the in-repo gitignored copy if the canonical
        # location isn't there
        CRED_FILE="${REPO_ROOT}/x_archive/secrets/lst-credentials.txt"
    fi
    if [[ -f "$CRED_FILE" ]]; then
        # Match the Postgres password line specifically.
        # File format: "Password: Joget@DB#2026!" (the second one)
        PGPASSWORD=$(awk -F': ' '/^Password: /{print $2; exit}' "$CRED_FILE" \
                     | tail -1 | tr -d '[:space:]')
        # If multiple Password lines, take the second (Joget admin is first, DB is second)
        # Simpler: take the line under "Database Access"
        PGPASSWORD=$(awk '/Database Access:/{found=1} found && /^Password: /{print $2; exit}' "$CRED_FILE" | tr -d '[:space:]')
        export PGPASSWORD
    fi
fi

if [[ -z "${PGPASSWORD:-}" ]]; then
    echo "ERROR: PGPASSWORD not set and not found in ~/IdeaProjects/rsr/secrets/lst-credentials.txt"
    echo "Either: export PGPASSWORD='...' before running, OR ensure the secrets file exists with the Database Access Password line."
    exit 1
fi

# ─── Parse flags ─────────────────────────────────────────────────────────
DO_PUSH=0
DO_COMMIT=1
DRY_RUN=0
for arg in "$@"; do
    case "$arg" in
        --push)       DO_PUSH=1 ;;
        --no-commit)  DO_COMMIT=0 ;;
        --dry-run)    DRY_RUN=1; DO_COMMIT=0 ;;
        -h|--help)
            sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "Unknown flag: $arg" >&2
            exit 1
            ;;
    esac
done

# ─── Run the pull ────────────────────────────────────────────────────────
echo "[sync] Pulling app state from Joget (this takes ~2 min for master-data)…"
python3 tooling/sync_pull.py

# ─── Show diff stats ─────────────────────────────────────────────────────
echo ""
echo "[sync] Diff summary:"
CHANGED=$(git status --porcelain app/ | wc -l | tr -d ' ')
if [[ "$CHANGED" == "0" ]]; then
    echo "  (no changes — deployed state matches repo)"
    exit 0
fi
echo "  $CHANGED files changed under app/"
git diff --stat app/ | tail -5

# ─── Dry-run early-exit ──────────────────────────────────────────────────
if [[ "$DRY_RUN" == "1" ]]; then
    echo ""
    echo "[sync] Dry-run: stopping here. Run without --dry-run to commit."
    exit 0
fi

# ─── Stage + commit ──────────────────────────────────────────────────────
if [[ "$DO_COMMIT" == "1" ]]; then
    echo ""
    echo "[sync] Staging app/ changes…"
    git add app/

    TIMESTAMP=$(date '+%Y-%m-%d %H:%M %Z')
    BREAKDOWN=$(git diff --cached --name-only app/ | awk -F/ '{print $2}' | sort | uniq -c | awk '{printf "  - %s/: %d files\n", $2, $1}')
    git commit -q -m "sync: pull App Composer edits from Joget ($TIMESTAMP)

Auto-generated by tooling/sync.sh. Captures the current deployed
state of forms/datalists/userviews/master-data into the repo.

Breakdown:
$BREAKDOWN
Run \`git show\` to inspect the exact JSON/YAML changes per asset."

    echo "[sync] Committed:"
    git log -1 --oneline
fi

# ─── Optional push ───────────────────────────────────────────────────────
if [[ "$DO_PUSH" == "1" ]]; then
    echo ""
    echo "[sync] Pushing to origin/main…"
    git push origin main
    echo "[sync] Done. Public repo updated."
else
    echo ""
    echo "[sync] Done. To push:  git push origin main"
fi
